export { default as HeroSection } from "./Hero"
export { default as FeatureSection } from "./Features"
export { ContentSectionOne } from "./Content"
export { default as SeachSection } from "./Search"
export { default as TestimonialSection } from "./Testimonial"
export { default as PricingSection } from "./Pricing"
export { default as TeamSection } from "./Team"
export { default as FooterSection } from "./Footer"
